# ===================================
#  List Behavior Config
# ===================================

title: indikator.gallery::lang.menu.categories
list: ~/plugins/indikator/gallery/models/categories/columns.yaml
modelClass: Indikator\Gallery\Models\Categories
recordUrl: indikator/gallery/categories/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true
defaultSort:
    column: name
    direction: asc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
