# ===================================
#  List Behavior Config
# ===================================

title: indikator.gallery::lang.menu.albums
list: ~/plugins/indikator/gallery/models/albums/columns.yaml

modelClass: Indikator\Gallery\Models\Albums
recordUrl: indikator/gallery/albums/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: date
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
