# ===================================
#  Form Behavior Config
# ===================================

name: indikator.gallery::lang.title.albums
form: @/plugins/indikator/gallery/models/albums/fields.yaml
modelClass: Indikator\Gallery\Models\Albums
defaultRedirect: indikator/gallery/albums

create:
    redirect: indikator/gallery/albums
    redirectClose: indikator/gallery/albums

update:
    redirect: indikator/gallery/albums
    redirectClose: indikator/gallery/albums
